### ISSUE TITLE
[Bug] Only fullscreen opaque activities can request orientation

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-mobile-wallet#59]
There is an issue reported by Google Play Console in pre-launch report details.

```
FATAL EXCEPTION: main
Process: io.casperdash.casperwallet, PID: 12329
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.casperdash.casperwallet/io.casperdash.casperwallet.MainActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
	at android.app.Activity.onCreate(Activity.java:1038)
	at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:81)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:154)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:312)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45)
	at io.casperdash.casperwallet.MainActivity.onCreate(MainActivity.java:29)
	at android.app.Activity.performCreate(Activity.java:7174)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
```

![Screen Shot 2022-03-21 at 13 51 57](https://user-images.githubusercontent.com/4486806/159216176-89836ae1-9696-47e6-824c-24ed1f46b1a4.png)

**Comment by ThanhNguyen140797** [comment]
@gaupoit please check this #82
